# -*- mode: ruby -*-
# # vi: set ft=ruby :
 
# Specify minimum Vagrant version and Vagrant API version
#Vagrant.require_version ">= 1.6.0"
#VAGRANTFILE_API_VERSION = "2"
 
# Require YAML module
require 'yaml'
 
# Read YAML file with box details
servers = YAML.load_file('servers.yaml')
 
# Create boxes
Vagrant.configure("2") do |config|
#Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 
  # Iterate through entries in YAML file
  servers.each do |servers|
    config.vm.define servers["name"] do |srv|
      srv.vm.box = servers["box"]
	  srv.vm.hostname = servers["name"]
      srv.vm.network "public_network", ip: servers["ip"]
      srv.vm.provider :virtualbox do |vb|
        vb.name = servers["name"]
        vb.memory = servers["ram"]
			      # Install apps script
      srv.vm.provision :shell, path: servers["script"]
	     #srv.vm.provision :reload	
	     #srv.vm.provision :shell, path: "./.scripts/postscript.sh"
	 	end
    end
  end
end
 #end  
#end